### ISSUE TITLE
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block:

### ISSUE THREAD

**Issue by simplenotezy** [mikefrancis/laravel-secureheaders#12]
I am getting the following error:

    Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

This is my **secure-headers.php**

    <?php

    return [

        /*
         * X-Content-Type-Options
         *
         * Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
         *
         * Available Value: 'nosniff'
         */

        'x-content-type-options' => 'nosniff',

        /*
         * X-Download-Options
         *
         * Reference: https://msdn.microsoft.com/en-us/library/jj542450(v=vs.85).aspx
         *
         * Available Value: 'noopen'
         */

        'x-download-options' => 'noopen',

        /*
         * X-Frame-Options
         *
         * Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
         *
         * Available Value: 'deny', 'sameorigin', 'allow-from <uri>'
         */

        'x-frame-options' => 'sameorigin',

        /*
         * X-Permitted-Cross-Domain-Policies
         *
         * Reference: https://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html
         *
         * Available Value: 'all', 'none', 'master-only', 'by-content-type', 'by-ftp-filename'
         */

        'x-permitted-cross-domain-policies' => 'none',

        /*
         * X-XSS-Protection
         *
         * Reference: https://blogs.msdn.microsoft.com/ieinternals/2011/01/31/controlling-the-xss-filter
         *
         * Available Value: '1', '0', '1; mode=block'
         */

        'x-xss-protection' => '1; mode=block',

        /*
         * Referrer-Policy
         *
         * Reference: https://w3c.github.io/webappsec-referrer-policy
         *
         * Available Value: 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin',
         *                  'same-origin', 'strict-origin', 'strict-origin-when-cross-origin', 'unsafe-url'
         */

        'referrer-policy' => 'no-referrer',

        /*
         * HTTP Strict Transport Security
         *
         * Reference: https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security
         *
         * Please ensure your website had set up ssl/tls before enable hsts.
         */

        'hsts' => [
            'enable' => true,

            'max-age' => 15552000,

            'include-sub-domains' => true,
        ],

        /*
         * Public Key Pinning
         *
         * Reference: https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning
         *
         * hpkp will be ignored if hashes is empty.
         */

        'hpkp' => [
            'hashes' => [
                // [
                //     'algo' => 'sha256',
                //     'hash' => 'hash-value',
                // ],
            ],

            'include-sub-domains' => false,

            'max-age' => 15552000,

            'report-only' => false,

            'report-uri' => null,
        ],

        /*
         * Content Security Policy
         *
         * Reference: https://developer.mozilla.org/en-US/docs/Web/Security/CSP
         *
         * csp will be ignored if custom-csp is not null. To disable csp, set custom-csp to empty string.
         *
         * Note: custom-csp does not support report-only.
         */

        'custom-csp' => null,

        'csp' => [
            'report-only' => false,

            'report-uri' => null,

            'upgrade-insecure-requests' => false,

            // enable or disable the automatic conversion of sources to https
            'https-transform-on-https-connections' => true,

            'base-uri' => [
                //
            ],

            'default-src' => '*',

            'child-src' => [
                //
            ],

            'script-src' => [
                'allow' => [
                    'https://platform-api.sharethis.com',
                    'https://buttons-config.sharethis.com',
                    'https://l.sharethis.com',
                    'https://unpkg.com/',
                    'https://l.sharethis.com/',
                    'l.sharethis.com',
                    'https://count-server.sharethis.com',
                    'https://graph.facebook.com',
                    'https://www.googletagmanager.com',
                    'https://www.google-analytics.com'
                ],

                'hashes' => [
                    // ['sha256' => 'hash-value'],
                ],

                'nonces' => [
                    //
                ],

                'self' => true,

                'unsafe-inline' => true,

                'unsafe-eval' => true,
            ],

            'style-src' => [
                'allow' => [
                    'https://fonts.googleapis.com',
                ],

                'self' => true,

                'unsafe-inline' => true,
            ],

            'img-src' => [
                'allow' => [
                    'https://www.google-analytics.com'
                ],

                'types' => [
                    //
                ],

                'self' => true,

                'data' => true,
            ],

            /*
             * The following directives are all use 'allow' and 'self' flag.
             *
             * Note: default value of 'self' flag is false.
             */

            'font-src' => [
                'allow' => [
                    'https://fonts.gstatic.com'
                ],
                'self' => true,
                'data' => true,
            ],

            'connect-src' => '*',

            'form-action' => [
                //
            ],

            'frame-ancestors' => [
                //
            ],

            'media-src' => [
                //
            ],

            'object-src' => [
                //
            ],

            /*
             * plugin-types only support 'allow'.
             */

            'plugin-types' => [
                //
            ],
        ],

    ];

**Comment by mikefrancis** [comment]
Hi,

I think there is an issue with your config - the `csp` key's value should be a flat array, you have key/values in there which the secure headers library does not understand - see here:

https://github.com/aidantwoods/SecureHeaders#using-csp

**Comment by aidantwoods** [comment]
I'm working on some type safety related improvements which should help reject these kind of errors a little earlier.

Though, in theory arrays that are nested too deeply, at least for CSP, should already be throwing:
https://github.com/aidantwoods/SecureHeaders/blob/v2.0.1/src/SecureHeaders.php#L1728-L1730

Quick test throwing in the given CSP array seems to concur:
<img width="821" alt="screen shot 2018-01-02 at 20 19 13" src="https://user-images.githubusercontent.com/3288888/34498590-3f9a19ac-effa-11e7-8bd5-c45d5ae650a0.png">
(side note on there being a bug in the function claiming to throw the error in that message that was fixed, just not quite released yet).


Curious as to why the given error occurred, it isn't an error that SecureHeaders should be throwing, possibly from Laravel?

---
@simplenotezy 
Just as a side note, the current configuration does look a little strange – for example you've "disabled" `upgrade-insecure-requests`, but "enabled" `https-transform-on-https-connections` which is supposed to "enable or disable the automatic conversion of sources to https" (which is what `upgrade-insecure-requests` does, this other option isn't a valid directive, so browsers will ignore it).

By the way, booleans aren't supported here – to enable something just write the directive and either leave it as a value in the array (i.e. it will auto receive an `int` key), or map it to `null` ([syntax](https://github.com/aidantwoods/SecureHeaders/wiki/csp#array)). To disable a directive, just omit it (CSP generally behaves like a whitelist).
