### ISSUE TITLE
Tests aren't being run on Travis

### ISSUE THREAD

**Issue by aidantwoods** [mikefrancis/laravel-secureheaders#13]
https://travis-ci.org/mikefrancis/laravel-secureheaders/jobs/270058781#L528
![screen shot 2018-01-02 at 22 57 50](https://user-images.githubusercontent.com/3288888/34503466-62abdece-f010-11e7-852d-2cca9b8dea1f.png)

Initially I thought this might be a problem with absence of `--prefer-dist` in the `composer install`, but you have no `.gitattrubutes`, so the phpunit configuration should be being pulled.

I'd recommend branching and running `phpunit -v` in Travis to confirm that the config is indeed/not being loaded.

**Comment by mikefrancis** [comment]
This is very strange - some builds are being run but some aren't.

Will investigate and leave this open for now.
