### ISSUE TITLE
Support for Expect-CT header

### ISSUE THREAD

**Issue by simplenotezy** [mikefrancis/laravel-secureheaders#18]
See: https://tools.ietf.org/html/draft-ietf-httpbis-expect-ct-02 and https://scotthelme.co.uk/a-new-security-header-expect-ct/

**Comment by mikefrancis** [comment]
This would need to be enabled on the original https://github.com/aidantwoods/secureheaders package first.

**Comment by aidantwoods** [comment]
It's already supported (https://github.com/aidantwoods/secureheaders/wiki/expectCT) ;-)

Just needs the API mapping to from a config option.

**Comment by simplenotezy** [comment]
Great! Any docmentation on this?

**Comment by mikefrancis** [comment]
@simplenotezy Just need to pass in a bit of config:

```php

return [
  // ...

  'expectCT' => [
    'maxAge' => 31536000,
    'enforce' => true,
    'reportUri' =>'http://localhost',
  ],
];

```
