### ISSUE TITLE
[Question] about the documentation

### ISSUE THREAD

**Issue by IlCallo** [mikefrancis/laravel-secureheaders#25]
> If you are using Laravel 5.5+, you can then edit your composer.json to add the service provider and enable auto discovery: `<code>`

AFAIK this is not true, you don't need to add anything to enable auto-discovery. In a fresh installation of L5.5 it's enabled by default by the `"@php artisan package:discover"` command in the `"post-autoload-dump"` commands array.

> To add more secure headers to your entire application, add the ApplySecureHeaders middleware in the $middleware property of app/Http/Kernel.php class: `<code>`

Is there some use case in which it's actually needed to apply those headers to the general middleware stack (including in this way the JSON REST API requests) and not just to the web middleware? Aren't CSP and other security headers only used by browsers?

**Comment by IlCallo** [comment]
It's also worth noting that, at least in my case, putting the middleware before the `\Illuminate\Session\Middleware\StartSession::class,` web middleware broke my login flow (both via social login and normal Laravel login) and putting it before `\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,` broke the subsequent token-based api authentication.

I'd suggest to specify into the documentation that it must be added at the end of the "web" middleware group.

**Comment by mikefrancis** [comment]
Hi @IlCallo, thanks for reaching out. 

In regards to the service auto-discovery - this is a good point and this section can be removed. When we wrote this section, 5.5 wasn't even out so we were dealing with a bit of a "moving target".

Regarding the other 2 points about where to attach this middleware, it's really up to the developer. Like you mention, this breaks certain set ups but not all developers are using the Laravel Passport package or have endpoints which return JSON (like yourself) or indeed start sessions, if the application is stateless. This is why we don't really mention whereabouts in your application you should add the middleware, in the same way we don't tell you what to use as a CSP. You're the developer so if you're using this package, you'll need to know where it fits - this package isn't a silver bullet which will magically harden the security of your application, it needs to be configured as such.

However, I do agree the documentation could use a little explanation around this so this will be added.

Thanks for raising these points!

**Comment by IlCallo** [comment]
Thank you for doing the package :)
