### ISSUE TITLE
Laravel 6.0 Compatibility

### ISSUE THREAD

**Issue by pushchris** [mikefrancis/laravel-secureheaders#30]
It appears that this currently relies on `illuminate/http ^5.4` would be awesome to see the dependencies updated to allow for utilizing this with Laravel 6.0 and above.

**Comment by mikefrancis** [comment]
Hey, thanks for pointing this out.

Have released a new version (`v1.4`) which supports both Laravel 5 and 6.

**Comment by pushchris** [comment]
@mikefrancis fastest response time ever, love it! Thanks for taking care of it!
