### ISSUE TITLE
Support For Laravel 7.x

### ISSUE THREAD

**Issue by juliomotol** [mikefrancis/laravel-secureheaders#35]
Please add support for Laravel 7.x

![image](https://user-images.githubusercontent.com/21353103/75836671-9704ba80-5dfd-11ea-9020-3f68a9073053.png)

https://github.com/mikefrancis/laravel-secureheaders/blob/238cdb5acbae836f9b3c7b0ca5d3d9ff897c5c39/composer.json#L15-L16

Suggested fix:

    "illuminate/http": ">=5.4", 
    "illuminate/support": ">=5.4"

**Comment by mikefrancis** [comment]
Hi @juliomotol,

Not sure when I can take a look at this but you could always make a PR yourself 😄
