### ISSUE TITLE
report only

### ISSUE THREAD

**Issue by joedekangeroe** [mikefrancis/laravel-secureheaders#39]
Hi there

Thanks for this awesome laravel package.

 It seems quite easy to add into my existing projects and it is making a huge security impact.

However, it did not find a way to set the report only mode in the  conf file? Is this possible?

**Comment by aidantwoods** [comment]
I think if you use the config key `cspro` (instead of `csp`) then it'll deploy in report only mode :)

**Comment by joedekangeroe** [comment]
I'm sorry but `cspro` seems to do nothing at all.

**Comment by mikefrancis** [comment]
@joedekangeroe Can you post your config?

**Comment by joedekangeroe** [comment]
`<?php

return [
    // Toggles error reporting, see https://github.com/aidantwoods/SecureHeaders/wiki/errorReporting
    'errorReporting' => true,

    // Safe mode
    'safeMode' => false,

    // HSTS Strict-Transport-Security
    'hsts' => [
        'enabled' => true,
    ],

    // Content Security Policy
    'cspro' => [
        'default' => [
            'self',
        ],
        'img-src' => [
            '*',
            'data:',
            'unsafe-inline', // Allow images from anywhere
        ],
        'style-src' => [
            'self',
            'unsafe-inline', // Allow inline styles
            'https://fonts.googleapis.com', // Allow stylesheets from Google Fonts
        ],
        'font-src' => [
            'self',
            'data:',
            'https://fonts.gstatic.com', // Allow fonts from the Google Fonts CDN
        ],
        'report' => [
            'https://xyz..com/reports',
        ],
    ],


];`

**Comment by mikefrancis** [comment]
LGTM, I would maybe dump/debug your config at run time in the middleware just to check it's definitely not being overwritten or changed in any way.

**Comment by joedekangeroe** [comment]
I'm a bit lost now. How do I do that?

**Comment by mikefrancis** [comment]
@joedekangeroe Open up the middleware in `./vendor/mikefrancis/laravel-secureheaders/src/ApplySecureHeaders.php` folder and in the handle method add a `dd()` to dump the config, just to check it's definitely correct:

```php
public function handle(Request $request, Closure $next)
    {
        // Add the line below
        dd($this->config->get('secure-headers'));       
        $response = $next($request);
```

Then make a request to your application, you should see the config get output which you can ensure is correct.

**Comment by joedekangeroe** [comment]
array:5 [▼
  "errorReporting" => true
  "safeMode" => false
  "hsts" => array:1 [▼
    "enabled" => true
  ]
  "csp" => array:1 [▼
    "default" => "self"
  ]
  "cspro" => array:5 [▼
    "default" => array:2 [▼
      0 => "self"
      1 => "unsafe-inline"
    ]
    "img-src" => array:3 [▼
      0 => "*"
      1 => "data:"
      2 => "unsafe-inline"
    ]
    "style-src" => array:3 [▼
      0 => "self"
      1 => "unsafe-inline"
      2 => "https://fonts.googleapis.com"
    ]
    "font-src" => array:3 [▼
      0 => "self"
      1 => "data:"
      2 => "https://fonts.gstatic.com"
    ]
    "report" => array:1 [▼
      0 => "https://xyz..com/reports"
    ]
  ]
]

**Comment by mikefrancis** [comment]
@joedekangeroe It looks like you have both `csp` and `cspro` config. I'm not sure you need them both.

I'm confident this is not an issue with the package so if you need support I would post on StackOverflow or something like that, I'm afraid I don't really have bandwidth to support with individual cases at the moment.
