### ISSUE TITLE
Make some config settings determined by Laravel environment (feature request)

### ISSUE THREAD

**Issue by DeftNerd** [mikefrancis/laravel-secureheaders#8]
Rather than 
```
    'hsts' => [
        'enabled' => true,
        'safeMode' => false,
    ],

```
A more interesting option would be 
```
    'hsts' => [
        'enabled' => auto,
        'safeMode' => auto,
    ],
```

In this scenario, the package could make configuration decisions based on Laravel's enviroment setting ('local', 'testing', production') or debug setting ('true', 'false')

Perhaps the default setting for HSTS would be enabled for local and production environments, but disabled for testing... but safemode would be enabled if debug is set to true?

**Comment by mikefrancis** [comment]
Hi, thanks for your feedback.

You can set the config values to whatever you like, for instance:

```php
<?php

return [
  'hsts' => [
    'enabled' => env('HSTS_ENABLED', false),
  ],
];
```

You could use existing environment variables to help formulate the decision, so please feel free to publish the config and play with these values 🙂
