### ISSUE TITLE
Safe Mode affects more than HSTS

### ISSUE THREAD

**Issue by aidantwoods** [mikefrancis/laravel-secureheaders#9]
From the README

```php
    // HSTS Strict-Transport-Security
    'hsts' => [
        'enabled' => true,
        'safeMode' => false,
    ],
```

Maybe I should add more examples to the docs 😉 

Safe mode will neuter these headers:
* HSTS (will cap at 1 day, and remove `includeSubDomains` and `preload`)
* HPKP (will cap at 10 seconds, and remove `includeSubDomains`)
* Expect-CT (will remove `enforce`)

You could probably work a per header setting (by manually adding ones not set as safe mode exceptions), or just move safe mode out to its own config setting (probably more future proof if more headers are wrapped into it).

**Comment by mikefrancis** [comment]
@aidantwoods PR there if you want to take a look? 😉
